### ISSUE TITLE
Add new navigation diagram

### ISSUE THREAD

**Issue by campfire29** [cloudmesh/cloudmesh-nist#84]
The new navigation diagram (NIST Big Data Interoperability Framework Documents Navigation Diagram) should be added after the new paragraph introducing the figure (at the end of section 1.4 Report Structure).
[NBDIFDocNavigationFig_2019-05-28_LA.pptx](https://github.com/cloudmesh/cloudmesh-nist/files/3270828/NBDIFDocNavigationFig_2019-05-28_LA.pptx)

**Comment by laszewsk** [comment]
figure included
