### ISSUE TITLE
Remove reference to future work

### ISSUE THREAD

**Issue by campfire29** [cloudmesh/cloudmesh-nist#85]
We are removing references to future work on the documents. The paragraph in Section 1.3, Report Production might need to be removed.

This document is expected to grow with the help of contributions from
the community to achieve a comprehensive set of interfaces that will be
usable for the implementation of Big Data Architectures. To achieve
technical and high-quality document content, this document will go
through a public comment period along with NIST internal review.

**Comment by laszewsk** [comment]
removed
